package ruledefine

import (
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestAWS(t *testing.T) {
	tests := []struct {
		name           string
		truePositives  []string
		falsePositives []string
	}{
		{
			name: "AWS validation",
			truePositives: []string{
				"AWS_token: \"AKIALALEMEL33243OLIB\"",
				"var AWSToken string = \"AKIALALEMEL33243OLIB\"",
				"var AWSToken = \"AKIALALEMEL33243OLIB\"",
				"AWSToken = 'AKIALALEMEL33243OLIB'",
				"  \"AWSToken\" => \"AKIALALEMEL33243OLIB\"",
				"AWSToken = \"AKIALALEMEL33243OLIB\"",
				"<AWSToken>\n    AKIALALEMEL33243OLIB\n</AWSToken>",
				"AWSToken := \"AKIALALEMEL33243OLIB\"",
				"String AWSToken = \"AKIALALEMEL33243OLIB\";",
				"$AWSToken .= \"AKIALALEMEL33243OLIB\"",
				"AWSToken = \"AKIALALEMEL33243OLIB\"",
				"AWS_TOKEN ::= \"AKIALALEMEL33243OLIB\"",
				"AWS_TOKEN ?= \"AKIALALEMEL33243OLIB\"",
				"AWSToken=\"AKIALALEMEL33243OLIB\"",
				"AWSToken=AKIALALEMEL33243OLIB",
				"AWSToken = AKIALALEMEL33243OLIB",
				"{\n    \"AWS_token\": \"AKIALALEMEL33243OLIB\"\n}",
				"string AWSToken = \"AKIALALEMEL33243OLIB\";",
				"AWSToken := `AKIALALEMEL33243OLIB`",
				"AWS_TOKEN := \"AKIALALEMEL33243OLIB\"",
				"AWS_token: AKIALALEMEL33243OLIB",
				"System.setProperty(\"AWS_TOKEN\", \"AKIALALEMEL33243OLIB\")",
				"AWS_TOKEN = \"AKIALALEMEL33243OLIB\"",
				"AWS_TOKEN :::= \"AKIALALEMEL33243OLIB\"",
				"{\"config.ini\": \"AWS_TOKEN=AKIALALEMEL33243OLIB\\nBACKUP_ENABLED=true\"}",
				"AWS_token: 'AKIALALEMEL33243OLIB'",
				"{\n    \"AWS_token\": \"AKIAYX3S5I3WAP6HEXCK\"\n}",
				"string AWSToken = \"AKIAYX3S5I3WAP6HEXCK\";",
				"AWS_TOKEN :::= \"AKIAYX3S5I3WAP6HEXCK\"",
				"AWSToken = \"AKIAYX3S5I3WAP6HEXCK\"",
				"AWS_token: AKIAYX3S5I3WAP6HEXCK",
				"var AWSToken string = \"AKIAYX3S5I3WAP6HEXCK\"",
				"AWSToken := `AKIAYX3S5I3WAP6HEXCK`",
				"String AWSToken = \"AKIAYX3S5I3WAP6HEXCK\";",
				"System.setProperty(\"AWS_TOKEN\", \"AKIAYX3S5I3WAP6HEXCK\")",
				"AWS_TOKEN = \"AKIAYX3S5I3WAP6HEXCK\"",
				"AWSToken=\"AKIAYX3S5I3WAP6HEXCK\"",
				"<AWSToken>\n    AKIAYX3S5I3WAP6HEXCK\n</AWSToken>",
				"AWS_token: \"AKIAYX3S5I3WAP6HEXCK\"",
				"$AWSToken .= \"AKIAYX3S5I3WAP6HEXCK\"",
				"AWSToken = \"AKIAYX3S5I3WAP6HEXCK\"",
				"  \"AWSToken\" => \"AKIAYX3S5I3WAP6HEXCK\"",
				"AWS_TOKEN := \"AKIAYX3S5I3WAP6HEXCK\"",
				"{\"config.ini\": \"AWS_TOKEN=AKIAYX3S5I3WAP6HEXCK\\nBACKUP_ENABLED=true\"}",
				"AWS_token: 'AKIAYX3S5I3WAP6HEXCK'",
				"AWSToken := \"AKIAYX3S5I3WAP6HEXCK\"",
				"var AWSToken = \"AKIAYX3S5I3WAP6HEXCK\"",
				"AWSToken = 'AKIAYX3S5I3WAP6HEXCK'",
				"AWS_TOKEN ::= \"AKIAYX3S5I3WAP6HEXCK\"",
				"AWS_TOKEN ?= \"AKIAYX3S5I3WAP6HEXCK\"",
				"AWSToken=AKIAYX3S5I3WAP6HEXCK",
				"AWSToken = AKIAYX3S5I3WAP6HEXCK",
				"System.setProperty(\"AWS_TOKEN\", \"ASIAYX3S5I3WAP6HEXCK\")",
				"AWS_TOKEN := \"ASIAYX3S5I3WAP6HEXCK\"",
				"AWS_TOKEN ::= \"ASIAYX3S5I3WAP6HEXCK\"",
				"AWSToken=ASIAYX3S5I3WAP6HEXCK",
				"{\n    \"AWS_token\": \"ASIAYX3S5I3WAP6HEXCK\"\n}",
				"AWS_token: 'ASIAYX3S5I3WAP6HEXCK'",
				"  \"AWSToken\" => \"ASIAYX3S5I3WAP6HEXCK\"",
				"<AWSToken>\n    ASIAYX3S5I3WAP6HEXCK\n</AWSToken>",
				"AWS_token: \"ASIAYX3S5I3WAP6HEXCK\"",
				"var AWSToken = \"ASIAYX3S5I3WAP6HEXCK\"",
				"AWS_TOKEN = \"ASIAYX3S5I3WAP6HEXCK\"",
				"AWS_TOKEN :::= \"ASIAYX3S5I3WAP6HEXCK\"",
				"AWS_TOKEN ?= \"ASIAYX3S5I3WAP6HEXCK\"",
				"AWSToken = \"ASIAYX3S5I3WAP6HEXCK\"",
				"AWSToken = ASIAYX3S5I3WAP6HEXCK",
				"AWS_token: ASIAYX3S5I3WAP6HEXCK",
				"string AWSToken = \"ASIAYX3S5I3WAP6HEXCK\";",
				"var AWSToken string = \"ASIAYX3S5I3WAP6HEXCK\"",
				"AWSToken := \"ASIAYX3S5I3WAP6HEXCK\"",
				"AWSToken := `ASIAYX3S5I3WAP6HEXCK`",
				"String AWSToken = \"ASIAYX3S5I3WAP6HEXCK\";",
				"AWSToken=\"ASIAYX3S5I3WAP6HEXCK\"",
				"{\"config.ini\": \"AWS_TOKEN=ASIAYX3S5I3WAP6HEXCK\\nBACKUP_ENABLED=true\"}",
				"$AWSToken .= \"ASIAYX3S5I3WAP6HEXCK\"",
				"AWSToken = 'ASIAYX3S5I3WAP6HEXCK'",
				"AWSToken = \"ASIAYX3S5I3WAP6HEXCK\"",
				"AWS_TOKEN = \"ABIAVD5OL7E6ZYKOWCSQ\"",
				"AWS_TOKEN := \"ABIAVD5OL7E6ZYKOWCSQ\"",
				"AWS_TOKEN :::= \"ABIAVD5OL7E6ZYKOWCSQ\"",
				"AWSToken=\"ABIAVD5OL7E6ZYKOWCSQ\"",
				"<AWSToken>\n    ABIAVD5OL7E6ZYKOWCSQ\n</AWSToken>",
				"AWS_token: ABIAVD5OL7E6ZYKOWCSQ",
				"string AWSToken = \"ABIAVD5OL7E6ZYKOWCSQ\";",
				"AWSToken := `ABIAVD5OL7E6ZYKOWCSQ`",
				"AWS_TOKEN ?= \"ABIAVD5OL7E6ZYKOWCSQ\"",
				"AWS_token: \"ABIAVD5OL7E6ZYKOWCSQ\"",
				"var AWSToken = \"ABIAVD5OL7E6ZYKOWCSQ\"",
				"$AWSToken .= \"ABIAVD5OL7E6ZYKOWCSQ\"",
				"System.setProperty(\"AWS_TOKEN\", \"ABIAVD5OL7E6ZYKOWCSQ\")",
				"AWS_TOKEN ::= \"ABIAVD5OL7E6ZYKOWCSQ\"",
				"AWSToken = \"ABIAVD5OL7E6ZYKOWCSQ\"",
				"AWSToken = ABIAVD5OL7E6ZYKOWCSQ",
				"{\"config.ini\": \"AWS_TOKEN=ABIAVD5OL7E6ZYKOWCSQ\\nBACKUP_ENABLED=true\"}",
				"AWS_token: 'ABIAVD5OL7E6ZYKOWCSQ'",
				"var AWSToken string = \"ABIAVD5OL7E6ZYKOWCSQ\"",
				"String AWSToken = \"ABIAVD5OL7E6ZYKOWCSQ\";",
				"AWSToken = \"ABIAVD5OL7E6ZYKOWCSQ\"",
				"AWSToken=ABIAVD5OL7E6ZYKOWCSQ",
				"{\n    \"AWS_token\": \"ABIAVD5OL7E6ZYKOWCSQ\"\n}",
				"AWSToken := \"ABIAVD5OL7E6ZYKOWCSQ\"",
				"AWSToken = 'ABIAVD5OL7E6ZYKOWCSQ'",
				"  \"AWSToken\" => \"ABIAVD5OL7E6ZYKOWCSQ\"",
				"$AWSToken .= \"ACCAVD5OL7E6ZYKOWCSQ\"",
				"AWSToken = \"ACCAVD5OL7E6ZYKOWCSQ\"",
				"System.setProperty(\"AWS_TOKEN\", \"ACCAVD5OL7E6ZYKOWCSQ\")",
				"AWS_TOKEN = \"ACCAVD5OL7E6ZYKOWCSQ\"",
				"AWS_token: ACCAVD5OL7E6ZYKOWCSQ",
				"AWS_token: \"ACCAVD5OL7E6ZYKOWCSQ\"",
				"string AWSToken = \"ACCAVD5OL7E6ZYKOWCSQ\";",
				"var AWSToken = \"ACCAVD5OL7E6ZYKOWCSQ\"",
				"AWS_TOKEN :::= \"ACCAVD5OL7E6ZYKOWCSQ\"",
				"AWSToken = ACCAVD5OL7E6ZYKOWCSQ",
				"<AWSToken>\n    ACCAVD5OL7E6ZYKOWCSQ\n</AWSToken>",
				"var AWSToken string = \"ACCAVD5OL7E6ZYKOWCSQ\"",
				"AWSToken := `ACCAVD5OL7E6ZYKOWCSQ`",
				"AWSToken = 'ACCAVD5OL7E6ZYKOWCSQ'",
				"  \"AWSToken\" => \"ACCAVD5OL7E6ZYKOWCSQ\"",
				"AWS_TOKEN ::= \"ACCAVD5OL7E6ZYKOWCSQ\"",
				"AWS_TOKEN ?= \"ACCAVD5OL7E6ZYKOWCSQ\"",
				"AWSToken = \"ACCAVD5OL7E6ZYKOWCSQ\"",
				"{\n    \"AWS_token\": \"ACCAVD5OL7E6ZYKOWCSQ\"\n}",
				"{\"config.ini\": \"AWS_TOKEN=ACCAVD5OL7E6ZYKOWCSQ\\nBACKUP_ENABLED=true\"}",
				"AWSToken := \"ACCAVD5OL7E6ZYKOWCSQ\"",
				"AWS_TOKEN := \"ACCAVD5OL7E6ZYKOWCSQ\"",
				"AWSToken=\"ACCAVD5OL7E6ZYKOWCSQ\"",
				"AWSToken=ACCAVD5OL7E6ZYKOWCSQ",
				"AWS_token: 'ACCAVD5OL7E6ZYKOWCSQ'",
				"String AWSToken = \"ACCAVD5OL7E6ZYKOWCSQ\";",
			},
			falsePositives: []string{
				`key = AKIAXXXXXXXXXXXXXXXX`,           // Low entropy
				`aws_access_key: AKIAIOSFODNN7EXAMPLE`, // Placeholder
				`msgstr "Näytä asiakirjamallikansio."`, // Lowercase
				`TODAYINASIAASACKOFRICEFELLOVER`,       // wrong length
				`CTTCATAGGGTTCACGCTGTGTAAT-ACG--CCTGAGGC-CACA-AGGGGACTTCAGCAACCGTCGGG-GATTC-ATTGCCA-A--TGGAAGCAATC-TA-TGGGTTA-TCGCGGAGTCCGCAAAGACGGCCAGTATG-AAGCAGATTTCGCAC-CAATGTGACTGCATTTCGTG-ATCGGGGTAAGTA-TC-GCCGATTC-GC--CCGTCCA-AGT-CGAAG-TA--GGCAATATAAAGCTGC-CATTGCCGAAGCTATCTCGCTA-TACTTGAT-AATCGGCGG-TAG-CACAG-GTCGCAGTATCG-AC-T--AGG-CCTCTCAAAAGTT-GGGTCCCGGCCTCTGGGAAAAACACCTCT-A-AGCGTCAATCAGCTCGGTTTCGCATATTA-TGATATCCCCCGTTGACCAATTGA--TAGTACCCGAGCTTACCGTCGG-ATTCTGGAGTCTT-ATGAGGTTACCGACGA-CGCAGTACCATAAGT-GCGCAATTTGACTGTTCCCGTCGAGTAACCA-AGCTTTGCTCA-CCGGGATGCGCGCCGATGTGACCAGGGGGCGCATGTTACATTGAC-A-GCTGGATCATGTTATGAC-GTGGGTC-ATGCTAAAAGCCTAAAGGACGGT-GCATTAGTAT-TACCGGGACCTCATATCAATGCGCTCGCTAGTTCCTCTTCTCTTGATAACGTATATGCGTCAGGCGCCCGTCCGCCTCCAATACGTG-ACAACGTC-AGTACTGAGCCTC--AA-ACATCGTCTTGTTCG-CC-TACAAAGGATCGGTAGAAAACTCAATATTCGGGTATAAGGTCGTAGGAAGTGTGTCGCCCAGGGCCG-CTAGA-AGCGCACACAAGCG-CTCCTGTCAAGGAGTTG-GTGAAAA-ATGAAC--GACT-ATTGCGTCAC--CTACCTCT-AAGTTTTT-GACAATTTCATGGACGAATTGA-AGCGTCCACAAGCATCTGCCGTAGATATGCGGTAGGTTTTTACATATG-TCACTGCAGAGTCACGGACA-CACATCGCTGTCAAAATGCTCGTACCTAGT-GT-TTGCGATCCCCC-GCGGCATTA-TCTTTTGAACCCTCGTCCCTGTGG-CTCTGATGATTGAG-GTCTGTA-TTCCCTCGTTGTGGGGGGATTGGACCTT-TGTATAGGTTCTTTAACCG-ATGGGGGGCCG--ATCGA-A-TA-TGCTCCTGTTTGCCCCGAACCTT-ACCTCGG-TCCAGACA-CTAAGAAAAACCCC-C-ACTGTAAGGTGCTGAGCCTTTGGATAGCC-CGCGAATGAT-CC-TAGTTGACAA-CTGAACGCGCTCGAACA-TGCCC-GCCCTCTGA--CTGCTGTCTG-GCACCTTTAGACACGCGTCGAC-CATATATT-AGCGCTGTCTGTGG-AGGT-TGTGTCTTGTTGCTCA-CT-CATTATCTGT-AACTGGCTCC-CTC-CCAT-TGGCGTCTTTACACCAACCGCTAGGTTACAGTGCA-TCTAGCGCCTATTATCAGGGCGT-TTGCAGCGGCGCGGTGGCTATGT-GTTAGACATATC-CTTACACTGTATGCTAG-AGCAAGCCAC-TCTGAATGGGTTGC-CGATGAATGA-TCTTGATC-GAGCTCGCA-AC---TACATGGAGTCCGAAGTGAACCTACGGATGATCGTATTCCAACACGAGGATC-TATACGTATAGG-A-GGCG-TAATCCACAATTTAGTAACTCTTGACGC---GGATGAAAAT-GTCGTTACACCTTCCAGAGGCTCGG-GTATATATATGACCT--TGTGATTGAGGACGATCTAGAATAA-CT-GT-G-CT-AAAGTACAGTAGTTTCTATGT-GGTAGGTGGAGAATACAGAGTAG-ATGATTC-GTGGGCCACA-C--T-ACTTTCAT-TAGAGCAGAGA-C-GTGAGTGAGTTTTACACTAGCCAGATGGACCG-GTGA-AGTCTAACAGCCACCGCTT-GTGAGGTCGTTTCCCAGTC-ACCCTACTACAGGCAAAAACTCAGTGT-CC-GTGA-GTGCGTTAGTGATATTCCCTAACGGTTAGGTAACT-CATGAATTCA-AT-TAAGCGTGTCC-CGGT-CACGCCCCCATGGGGGCCTTCTTGGGAGG--AGCATCTTAT--AT-GCTCACGTGGTT-GATAGG-A-T-AATACACTTTTAGTCAGTCCATCAATAAC-AAAGGAAC---CAGGTGGTCGCAGATA-TCCCGCTGATATAGCACTGTGTAAACTCAGGTGATA-CTAAGC--GCTCTAAT-ACG-CTTAATGGCAATGCCCAGTTC--ACGACTAGCTTATGAGGCCCAGCTATGGACTGCGGC-GGCATGTCGGC-GATGGTTGCCCTCGCCCTAAATTATGTACGA-T-ACCGCCT-CTTGTTCT-CCGCCCATAGGGT-C--AGCAGGCGATAGACTCCCAGAAATTTCCTCGTCGT-CCGAATAAGACTAACACGACTA-TT-CCTCTAC-GT-G-AA-CTTATCA-CAAATG-GCT-TACC-TAGGTGGTGGCAGATCACTTTCCGGTG-TATTACGAATTGACGCATACCGAC-A-CGC-GCTTGTTGGATAATCGACTCTAACCTCCTCTCTGGCACATGT-GCTGGATTACCTC-TATTTT-TCTCGCTTAG--GGAACG-T-CCTCTGTCGCGTGAG-GTACGTTTCACGGGAG-CGGCTTGTTCATGCCACGTCCATTATCGA-AGTG-C-GTAAGG-A-GAGCCCTA--GACTCTACACGGAAA-TC-AAC-GTAGAAGGCTC-A-CT`,
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			rule := ConvertNewRuleToGitleaksRule(AWS())
			d := createSingleRuleDetector(rule)

			// validate true positives if any specified
			for _, truePositive := range tt.truePositives {
				findings := d.DetectString(truePositive)
				assert.GreaterOrEqual(t, len(findings), 1, fmt.Sprintf("failed to detect true positive: %s", truePositive))
			}

			// validate false positives if any specified
			for _, falsePositive := range tt.falsePositives {
				findings := d.DetectString(falsePositive)
				assert.Equal(t, 0, len(findings), fmt.Sprintf("unexpectedly found false positive: %s", falsePositive))
			}
		})
	}
}
