name: Run 2ms Scan and Upload to S3

on:
  push:

jobs:
  scan-and-upload:
    runs-on: ubuntu-latest  

    steps:
      - name: Check out repository
        uses: actions/checkout@v4  

      - name: Run 2ms Scan
        uses: miguel-neiva01/2ms-github-action@v1.6.5 
        id: twoms_scan

      - name: Get Results Directory
        id: get_results_dir
        run: |
          echo "results_dir=results" >> $GITHUB_ENV
          echo "Results Directory: ${{ env.results_dir }}"  

      - name: Upload 2ms Scan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: ${{ env.results_dir }}

      - name: Set S3 Destination Path
        id: set_s3_path
        run: |
          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
          PR_NUMBER="${{ github.event.number }}"
          VERSION="v3.17.0"
          ENGINE="2ms"
          COMMIT_HASH="${{ github.sha }}"
          PR_OWNER="${{ github.actor }}"
          TARGET_BRANCH="master"  

          echo "destination_dir=s3://ces-results/${ENGINE}/${TARGET_BRANCH}/${BRANCH_NAME}/${VERSION}/pr-${PR_NUMBER}" >> $GITHUB_ENV 
          echo "results_dir=${{ env.results_dir }}" >> $GITHUB_ENV

      - name: Create metadata
        run: |
          mkdir -p "${{ env.results_dir }}"
    
          for artifact_dir in $(find $GITHUB_WORKSPACE -type d -name "results"); do
            artifact_name=$(basename $(dirname $artifact_dir))  # Nome do repositório (projeto)
            mkdir -p "${{ env.results_dir }}/${artifact_name}"
  
            mv "${artifact_dir}"/*.sarif "${{ env.results_dir }}/${artifact_name}/"
  
            echo "Moved SARIF file for artifact: ${artifact_name}"
          done
  
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo '{
            "timestamp": "'"${TIMESTAMP}"'",
            "branch": "'"${{ github.head_ref || github.ref_name }}"'",
            "pr_number": "'"${{ github.event.number }}"'",
            "version": "'"${VERSION}"'",
            "commit_hash": "'"${COMMIT_HASH}"'",
            "pr_owner": "'"${PR_OWNER}"'",
            "engine": "'"${ENGINE}"'"
          }' > "${{ env.results_dir }}/metadata.json"
  
          echo "Created directory structure:"
          tree "${{ env.results_dir }}"

      - name: Upload results to S3
        uses: shallwefootball/s3-upload-action@master
        with:
            aws_key_id: ${{ secrets.CES_BUCKET_AWS_ACCESS_KEY }}
            aws_secret_access_key: ${{ secrets.CES_BUCKET_AWS_SECRET_ACCESS_KEY }}
            aws_bucket:  ${{ secrets.CES_AWS_BUCKET }} 
            source_dir: ${{ env.results_dir }}
            destination_dir: ${{ env.destination_dir }}
