name: Run 2ms Scan and Upload to S3

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'  
jobs:
  scan-and-upload:
    runs-on: ubuntu-latest  

    steps:
      - name: Check out repository
        uses: actions/checkout@v4  

      - name: Run 2ms Scan
        uses: miguel-neiva01/2ms-github-action@v1.5.18  
        id: twoms_scan

      - name: Get Results Directory
        id: get_results_dir
        run: |
          echo "results_dir=results" >> $GITHUB_ENV
          echo "Results Directory: ${{ env.results_dir }}"  

      - name: Upload 2ms Scan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 2ms-results
          path: ${{ env.results_dir }}

      - name: Set S3 Destination Path
        id: set_s3_path
        run: |
          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
          PR_NUMBER="275"
          VERSION="v3.17.0"
          echo "destination_dir=2ms/${BRANCH_NAME}/${VERSION}/pr-${PR_NUMBER}" >> $GITHUB_ENV

      - name: Upload results to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.CES_BUCKET_AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.CES_BUCKET_AWS_SECRET_ACCESS_KEY }}
          aws_bucket: "ces-results" 
          source_dir: ${{ env.results_dir }}
          destination_dir: ${{ env.destination_dir }}
