
name: Codecov Scan

on:
  push:
    branches:
      - main 
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    runs-on: cx-public-ubuntu-x64

    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Set up Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version-file: go.mod
      env:
        GOPROXY: direct
        GONOSUMDB: "*"
        GOPRIVATE: https://github.com/CheckmarxDev/

    - name: Install dependencies 
      run: go install golang.org/x/tools/cmd/cover@latest

    - name: Run tests and generate coverage 
      run: |
        go test ./... -coverpkg=./... -v -coverprofile cover.out
                  
         
    - name: Upload coverage to Codecov
      uses: step-security/codecov-action@87e66f47a0f8ab4cae465a323eb9ec63d8b6b875 # v6.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} 
        files: ./cover.out  
        flags: target=auto
        fail_ci_if_error: true
        verbose: false
