name: Validate Conventional Commit title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  pr-lint:
    name: Lint PR Titles
    runs-on: ubuntu-latest
    steps:
      - uses: Weburz/pr-lint-action@2ecff97b8e96423f024b159426f8ca78e3f00a77
