name: validate-issues
on:
  issues:
    types: [opened, edited, reopened]
jobs:
  title-check:
    runs-on: ubuntu-latest
    env:
      BODY: ${{ github.event.issue.body }}
      TITLE: ${{ github.event.issue.title }}
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
        sparse-checkout: |
          .github/scripts/pr-issue-info/issue-fail.md
          .github/scripts/pr-issue-info/get_title_types.py
          .github/issue-title-types.yaml
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: python3 -m pip install --upgrade pip pyyaml
    - name: Check issue title
      env:
        FILE_PATH: .github/issue-title-types.yaml
      run: |
        regex=$(python3 .github/scripts/pr-issue-info/get_title_types.py)
        echo "Title regex: $regex"
        echo "$TITLE" | grep -Pq "$regex" || (echo "$ERROR_MSG" && echo "TITLE_CHECK_FAILED=true" >> $GITHUB_ENV)
    - name: Check for comment tag
      if: ${{ env.TITLE_CHECK_FAILED != 'true' }}
      run: |
        comments=$(curl -s -H "Authorization: token ${{ secrets.TWOMS_BOT_PAT}}" \
            -X GET "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments")
        if echo "$comments" | grep -q "title_check"; then
          echo "TAG_EXISTS=true" >> $GITHUB_ENV
        else
          echo "TAG_EXISTS=false" >> $GITHUB_ENV
        fi
    - name: Delete comment if title is fixed
      if: ${{ env.TAG_EXISTS == 'true' }}
      uses: thollander/actions-comment-pull-request@e4a76dd2b0a3c2027c3fd84147a67c22ee4c90fa
      with:
        message: |
          Deleting comment, please refresh the page...
        comment-tag: title_check
        mode: delete
        github-token: ${{ secrets.TWOMS_BOT_PAT }}
    - name: Add comment if title fails
      if: env.TITLE_CHECK_FAILED == 'true'
      uses: thollander/actions-comment-pull-request@e4a76dd2b0a3c2027c3fd84147a67c22ee4c90fa
      with:
        file-path: .github/scripts/pr-issue-info/issue-fail.md
        comment-tag: title_check
        mode: recreate
        create-if-not-exists: true
        github-token: ${{ secrets.TWOMS_BOT_PAT }}
    - name: Workflow failed
      if: env.TITLE_CHECK_FAILED == 'true'
      run: exit 1
  labels-check:
    runs-on: ubuntu-latest
    env:
      BODY: ${{ github.event.issue.body }}
      LABELS: ${{ toJson(github.event.issue.labels) }}
      TITLE: ${{ github.event.issue.title }}
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
        sparse-checkout: |
          .github/scripts/pr-issue-info/get_keywords.py
          .github/keywords.yaml
    - name: Install JQ
      run: sudo apt-get install jq
    - name: Add feature or feature request label
      run: |
        if [[ "$TITLE" == feat* ]] || echo "$TITLE $BODY" | grep -iqP "feature request" || echo "$BODY" | grep -iqP "Is your feature request related to a problem? Please describe." || echo "$BODY" | grep -iqP "Describe the solution you'd like" || echo "$BODY" | grep -iqP "Describe alternatives you've considered" || echo "$BODY" | grep -iqP "Additional context"; then
          if [[ "$IS_MEMBER" == "true" ]]; then
            echo "Adding 'feature' label..."
            curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels -d '{"labels": ["feature"]}'
          else
            echo "Adding 'feature request' label..."
            curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels -d '{"labels": ["feature request"]}'
          fi
        else
          if echo "$LABELS" | grep -q "feature request"; then
            echo "Removing 'feature request' label..."
            curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X DELETE -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels/feature%20request
          elif echo "$LABELS" | grep -q "feature"; then
            echo "Removing 'feature' label..."
            curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X DELETE -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels/feature
          fi
        fi
    - name: Add bug label
      run: |
        if echo "$TITLE $BODY" | grep -iqP "(\\b|_)bugs?(\\b|_)" || echo "$BODY" | grep -iqP "steps to reproduce" || echo "$BODY" | grep -iqP "actual behavior" || echo "$BODY" | grep -iqP "expected behavior"; then
          echo "Adding 'bug' label..."
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels -d '{"labels": ["bug"]}'
        else
          if echo "$LABELS" | grep -q "bug"; then
            echo "Removing 'bug' label..."
            curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X DELETE -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels/bug
          fi
        fi
    - name: Add bug label (extra)
      run: |
        if echo "$TITLE $BODY" | grep -iqP "(\\b|_)bugs?(\\b|_)" || echo "$BODY" | grep -iqP "steps to reproduce" || echo "$BODY" | grep -iqP "actual behavior" || echo "$BODY" | grep -iqP "expected behavior"; then
          echo "Adding 'bug' label (extra)..."
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels -d '{"labels": ["bug"]}'
        else
          if echo "$LABELS" | grep -q "bug"; then
            echo "Removing 'bug' label (extra)..."
            curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X DELETE -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels/bug
          fi
        fi